spring.application.name=springboot_security_app

jwt.secret=EoD8JEGHx9UNwofTvzqrVJqI73ghsooSzlQ9NGha3KcQtJohuvJArVF6V1zbvAVEwwodWQhoTu23i5Nb0n8RSg==

spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.datasource.username=app
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true